security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: pick@dropN3p@l
    key-pair-alias: pickNdropNepal
    key-pair-password: pick@dropN3p@l

#    keytool -genkey -alias pickNdropNepal -keyalg RSA -keystore "C:\Users\Keshar\Desktop\pick\auth-server\src\main\resources\keystore.jks"
#    keytool -list -rfc --keystore keystore.jks | openssl x509 -inform pem -pubkey -noout

spring:
  datasource:
    url: jdbc:mysql://oauthdb.cb7ov1w7gdyx.us-east-1.rds.amazonaws.com/oAuthDB
    username: keshar
    password: Keshar2908
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        type: trace

server:
  port: 9191
